### ISSUE TITLE
Cannot find module '@typescript-eslint/experimental-utils'

### ISSUE THREAD

**Issue by Jack-Works** [DimensionDev/eslint-plugin#4]
Error: Failed to load plugin '@dimensiondev' declared in '--config': Cannot find module '@typescript-eslint/experimental-utils'
Require stack:
- C:\Users\Jack\Workspace\Mask\node_modules\.pnpm\@dimensiondev+eslint-plugin@0.0.1-20220117062517-fd3cb01_eslint@8.7.0\node_modules\@dimensiondev\eslint-plugin\lib\rules\no-bigint.js
- C:\Users\Jack\Workspace\Mask\node_modules\.pnpm\@dimensiondev+eslint-plugin@0.0.1-20220117062517-fd3cb01_eslint@8.7.0\node_modules\@dimensiondev\eslint-plugin\lib\rules\index.js
- C:\Users\Jack\Workspace\Mask\node_modules\.pnpm\@dimensiondev+eslint-plugin@0.0.1-20220117062517-fd3cb01_eslint@8.7.0\node_modules\@dimensiondev\eslint-plugin\lib\index.js
- C:\Users\Jack\Workspace\Mask\node_modules\.pnpm\@eslint+eslintrc@1.0.5\node_modules\@eslint\eslintrc\dist\eslintrc.cjs

**Comment by septs** [comment]
latest version available
