### ISSUE TITLE
add `browser/no-persistence-storage` rule

### ISSUE THREAD

**Issue by septs** [DimensionDev/eslint-plugin#5]
https://github.com/DimensionDev/Maskbook/pull/6128#discussion_r857209722

**Comment by Jack-Works** [comment]
Actually, sessionStorage/indexedDB should also be banned inside Content Script.

**Comment by septs** [comment]
- `localStorage`
- `sessionStorage`
- `indexedDB`
- `document.cookie`
- `cookieStore`
