### ISSUE TITLE
prefer-early-return stylistic bug

### ISSUE THREAD

**Issue by binary64** [DimensionDev/eslint-plugin#8]
Hi, loving your suite of plugins! I've found one issue that made me go "hrmm" which was prefer-early-return seems to convert

```
() => {
  if (blah !== true) {
    // ...
    return true
  }
}
```
to
```
() => {
  if (!(blah !== true)) {
    // ...
    return true
  }
}
```
Now, it would seem tempted to fix this (?) however I have another idea, which is to leverage the power of eslint. I beleive it re-runs autofixes until the file stops changing. With this in mind, what if another rule could convert this:
```
if (!(blah !== true)) {
```
to
```
if (blah === true) {
```

**Comment by septs** [comment]
TODO: Invert the comparison sign
